stages:
  - pre
  - build

check_fprettify:pre:
  stage: pre
  image: alpine
  tags:
    - docker.meteo.physik.lmu.de
  before_script:
    - apk update && apk add bash git python3
  script:
    - echo "Checking that code base adheres to our code formatting standards"
    - echo "In case it doesnt, please run maint/fprettify.sh before you commit"
    - maint/fprettify.sh -d


.template_build_PETSC: &template_build_PETSC
    - export PETSC_DIR=$CI_PROJECT_DIR/$PETSC_DIR
    - echo -e "\e[0Ksection_start:`date +%s`:petsc_section[collapsed=true]\r\e[0KInstalling build dependencies to ${PETSC_DIR}/${PETSC_ARCH}"
    - misc/build_dependencies.sh "${PETSC_DIR}" "${PETSC_ARCH}" "${PETSC_PRECISION}" "${PETSC_DEBUGGING}" "${PETSC_64_INTEGERS}" "${PETSC_OPTS}"
    - cd $CI_PROJECT_DIR
    - echo -e "\e[0Ksection_end:`date +%s`:petsc_section\r\e[0K"

variables:
  TEST_FILTER_WITHOUT_LUTS: 'boxmc|LUT|test_pprts_symmetry|test_rrtm_lw_Bsrfc|test_rrtm_lw_sw|test_plexrt_fish|test_plexrt_rrtmg_lw_sw|test_pprts_absorption_by_coeff_divergence|test_plexrt_rayli'

# Build Stage
.build:default:
  stage: build
  script:
    - if [ ! -z "$MODULES" ]; then module load spack || echo 'no spack'; module load $MODULES || exit 1; module list; fi
    - mkdir -p build && cd build
    - cmake -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DCTEST_MPIRUN_FLAGS="$MPIRUN_FLAGS" -DMPIEXEC="$MPIEXEC" ${CMAKE_OPTS} .. || exit 1
    - make all -j || make all || exit 2
    - CMD="ctest --output-on-failure $CTEST_ARGS"
    - echo $CMD
    - $CMD &> >(tee $CI_PROJECT_DIR/test.log) || exit 3
  retry: 2
  variables:
    CTEST_ARGS: "-E 'boxmc|LUT'"
    BUILD_TYPE: RELEASE
    MPIEXEC: "mpirun"
    MPIRUN_FLAGS: '' #--allow-run-as-root;-A;bm0974;-p;shared
    CMAKE_OPTS: ''
    CC: mpicc
    FC: mpif90
    CXX: mpicxx
  artifacts:
    paths:
      - petsc/configure.log
      - test.log

ubuntu-latest:
  extends: .build:default
  image: ubuntu:latest
  before_script:
    - DEBIAN_FRONTEND=noninteractive apt-get -qq update
    - DEBIAN_FRONTEND=noninteractive apt-get -qq install -fy build-essential cmake gfortran git python3 openmpi-bin libopenmpi-dev libopenblas-dev curl pkg-config
    - *template_build_PETSC
  tags:
    - docker.meteo.physik.lmu.de
  variables:
    CTEST_ARGS: "-E ${TEST_FILTER_WITHOUT_LUTS}"
    MPIRUN_FLAGS: "--allow-run-as-root;--oversubscribe"
    PETSC_DIR: petsc
    PETSC_ARCH: default
    PETSC_PRECISION: double
    PETSC_64_INTEGERS: 0
    PETSC_DEBUGGING: 1
    BUILD_TYPE: RELEASE

ubuntu-rolling:
  extends: .build:default
  image: ubuntu:rolling
  before_script:
    - DEBIAN_FRONTEND=noninteractive apt-get -qq update
    - DEBIAN_FRONTEND=noninteractive apt-get -qq install -fy build-essential cmake gfortran git python3 openmpi-bin libopenmpi-dev libopenblas-dev curl pkg-config libeigen3-dev
    - *template_build_PETSC
  after_script:
    -  bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
  tags:
    - docker.meteo.physik.lmu.de
  variables:
    CTEST_ARGS: "-E ${TEST_FILTER_WITHOUT_LUTS}"
    MPIRUN_FLAGS: "--allow-run-as-root;--oversubscribe"
    PETSC_DIR: petsc
    PETSC_ARCH: default
    PETSC_PRECISION: single
    PETSC_64_INTEGERS: 1
    PETSC_DEBUGGING: 1
    BUILD_TYPE: RELEASE
    CMAKE_OPTS: '-DBUILD_RAYLI=ON -DENABLE_GCOV=ON -DCMAKE_Fortran_FLAGS=--std=legacy'
    CODECOV_TOKEN: "7d5206f3-f1e3-4704-8bc3-1ee443e4ee49"

# disabled because gcc image cannot apt install openmpi
#gcc_latest:gcov:
#  extends: .build:default
#  image: gcc:latest
#  before_script:
#    - DEBIAN_FRONTEND=noninteractive apt-get -qq update
#    - DEBIAN_FRONTEND=noninteractive apt-get -qq install -fy build-essential cmake git python3 openmpi-bin libopenmpi-dev libopenblas-dev curl pkg-config
#    - *template_build_PETSC
#  after_script:
#    -  bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
#  tags:
#    - docker.meteo.physik.lmu.de
#  variables:
#    CTEST_ARGS: "-E ${TEST_FILTER_WITHOUT_LUTS}"
#    MPIRUN_FLAGS: "--allow-run-as-root;--oversubscribe"
#    PETSC_DIR: petsc
#    PETSC_ARCH: default
#    PETSC_PRECISION: single
#    PETSC_64_INTEGERS: 0
#    PETSC_DEBUGGING: 0
#    BUILD_TYPE: RELEASE
#    CMAKE_OPTS: '-DCMAKE_Fortran_FLAGS=--std=legacy -DENABLE_GCOV=ON'
#    CODECOV_TOKEN: "7d5206f3-f1e3-4704-8bc3-1ee443e4ee49"

debian-testing:
  extends: .build:default
  image: debian:testing
  before_script:
    - DEBIAN_FRONTEND=noninteractive apt-get -qq update
    - DEBIAN_FRONTEND=noninteractive apt-get -qq install -fy build-essential cmake gfortran git python3 openmpi-bin libopenmpi-dev libopenblas-dev curl pkg-config
    - *template_build_PETSC
  tags:
    - docker.meteo.physik.lmu.de
  variables:
    CTEST_ARGS: "-E ${TEST_FILTER_WITHOUT_LUTS}"
    MPIRUN_FLAGS: "--allow-run-as-root;--oversubscribe"
    PETSC_DIR: petsc
    PETSC_ARCH: default
    PETSC_PRECISION: double
    PETSC_64_INTEGERS: 1
    PETSC_DEBUGGING: 1
    BUILD_TYPE: RELEASE
    CMAKE_OPTS: '-DCMAKE_Fortran_FLAGS=--std=legacy'


intel:
  extends: .build:default
  #image: intel/oneapi-hpckit
  image: intel/oneapi-hpckit:2021.4-devel-ubuntu18.04
  before_script:
    - DEBIAN_FRONTEND=noninteractive apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -fy cmake git m4 curl libcurl3-dev
    - *template_build_PETSC
  tags:
    - docker.meteo.physik.lmu.de
  variables:
    CTEST_ARGS: "-E ${TEST_FILTER_WITHOUT_LUTS}"
    PETSC_DIR: petsc
    PETSC_ARCH: default
    PETSC_PRECISION: single
    PETSC_64_INTEGERS: 0
    PETSC_DEBUGGING: 1
    BUILD_TYPE: RELEASE
    CC: mpiicc
    FC: mpiifort
    CXX: mpiicpc


intel:debug:
  extends: .build:default
  #image: intel/oneapi-hpckit
  image: intel/oneapi-hpckit:2021.4-devel-ubuntu18.04
  before_script:
    - DEBIAN_FRONTEND=noninteractive apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -fy cmake git m4 curl libcurl3-dev
    - *template_build_PETSC
  tags:
    - docker.meteo.physik.lmu.de
  variables:
    CTEST_ARGS: "-E ${TEST_FILTER_WITHOUT_LUTS}"
    PETSC_DIR: petsc
    PETSC_ARCH: default
    PETSC_PRECISION: double
    PETSC_64_INTEGERS: 1
    PETSC_DEBUGGING: 1
    BUILD_TYPE: DEBUG
    CC: mpiicc
    FC: mpiifort
    CXX: mpiicpc


# MIM runs
.build:mim:default:
  extends: .build:default
  before_script:
    - mkdir -p $CI_PROJECT_DIR/LUT; cp -rsn /project/meteo/homepages/Fabian.Jakub/TenstreamLUT/* $CI_PROJECT_DIR/LUT/
    - *template_build_PETSC
  tags:
    - slurm.meteo.physik.lmu.de
  variables:
    PETSC_DIR: petsc
    PETSC_ARCH: default
    PETSC_PRECISION: single
    PETSC_64_INTEGERS: 0
    PETSC_DEBUGGING: 1
    LUT_BASENAME: "$CI_PROJECT_DIR/LUT/LUT"
    SRUN_OPTIONS: "--time 02:00:00 --mem 6G -n 9"
    MPIEXEC: "srun"
    MPIRUN_FLAGS: '--mpi=pmix'
    CTEST_ARGS: '-E boxmc|LUT'

# GCC
mim:gcc:default:
  extends: .build:mim:default
  variables:
    BUILD_TYPE: RELEASE

mim:gcc:debug:
  extends: .build:mim:default
  variables:
    MODULES: "gcc/11.2.0"
    PETSC_PRECISION: double
    PETSC_64_INTEGERS: 1
    BUILD_TYPE: DEBUG

mim:icc:debug:
  extends: .build:mim:default
  variables:
    MODULES: "intel-oneapi-compilers/2021.4.0 intel-oneapi-mpi/2021.4.0-oneapi-2021.4.0"
    PETSC_PRECISION: double
    PETSC_64_INTEGERS: 1
    BUILD_TYPE: DEBUG
    CC: mpiicc
    FC: mpiifort
    CXX: mpiicpc


implicit:mim:gcc:debug:
  extends: .build:mim:default
  variables:
    BUILD_TYPE: DEBUG
    PETSC_OPTIONS: "-solar_dir_explicit no -solar_diff_explicit no -thermal_diff_explicit no"

explicit:mim:gcc:debug:
  extends: .build:mim:default
  variables:
    BUILD_TYPE: DEBUG
    PETSC_OPTIONS: "-solar_dir_explicit -solar_diff_explicit -thermal_diff_explicit -thermal_diff_pc_sor_omega .5 -solar_diff_pc_sor_omega .5"

matshell:mim:gcc:debug:
  extends: .build:mim:default
  variables:
    BUILD_TYPE: DEBUG
    PETSC_OPTIONS: "-solar_diff_shell -thermal_diff_shell"
