stages:
  - build

.template_build_PETSC: &template_build_PETSC
    - export PETSC_DIR=$CI_PROJECT_DIR/$PETSC_DIR
    - echo "Installing Petsc in ${PETSC_DIR}/${PETSC_ARCH}"
    - git clone -q --depth=1 https://gitlab.com/petsc/petsc.git $PETSC_DIR
    - cd $PETSC_DIR
    - >
      CMD="./configure
      --with-fortran
      --with-fortran-interfaces
      --with-precision=$PETSC_PRECISION
      --with-64-bit-indices=$PETSC_64_INTEGERS
      --with-debugging=$PETSC_DEBUGGING"
    - echo $CMD && $CMD && make PETSC_DIR=$PETSC_DIR PETSC_ARCH=$PETSC_ARCH all
    - cd $CI_PROJECT_DIR

# Build Stage
.build:default:
  stage: build
  script:
    - if [ ! -z "$MODULES" ]; then module load $MODULES || exit 1; module list; fi
    - mkdir -p build && cd build
    - cmake -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DCTEST_MPIRUN_FLAGS="$MPIRUN_FLAGS" -DMPIEXEC="$MPIEXEC" $CMAKE_OPTS .. || exit 1
    - make all -j || exit 2
    - CMD="ctest $CTEST_ARGS"
    - echo $CMD && $CMD || exit 3
  variables:
    CTEST_ARGS: "-V -E 'boxmc|LUT'"
    BUILD_TYPE: RELEASE
    MPIEXEC: "mpirun"
    MPIRUN_FLAGS: '' #--allow-run-as-root;-A;bm0974;-p;shared
    CMAKE_OPTS: ""

build:docker:ubuntu-rolling:
  extends: .build:default
  image: ubuntu:rolling
  before_script:
    - DEBIAN_FRONTEND=noninteractive apt-get -qq update
    - DEBIAN_FRONTEND=noninteractive apt-get -qq install -fy build-essential cmake gfortran git libhdf5-mpi-dev libnetcdf-dev libnetcdff-dev libopenblas-dev libopenmpi-dev m4 openmpi-bin python wget
    - *template_build_PETSC
  tags:
    - docker.meteo.physik.lmu.de
  variables:
    CTEST_ARGS: '-V -E boxmc|LUT|pfunit_test_pprts_symmetry|pfunit_test_rrtm_lw_Bsrfc|pfunit_test_rrtm_lw_sw'
    MPIRUN_FLAGS: "--allow-run-as-root;--oversubscribe"
    PETSC_DIR: petsc
    PETSC_ARCH: default
    PETSC_PRECISION: double
    PETSC_64_INTEGERS: 0
    PETSC_DEBUGGING: 1
    BUILD_TYPE: DEBUG

# MIM runs
.build:mim:default:
  extends: .build:default
  before_script:
    - mkdir -p $CI_PROJECT_DIR/LUT; cp -rsn /project/meteo/homepages/Fabian.Jakub/TenstreamLUT/* $CI_PROJECT_DIR/LUT/
  tags:
    - slurm.meteo.physik.lmu.de
  variables:
    LUT_BASENAME: "$CI_PROJECT_DIR/LUT/LUT"
    SRUN_OPTIONS: "--time 02:00:00 --mem 4G -n 9"
    MPIEXEC: "srun"
    MPIRUN_FLAGS: '--mpi=pmix'
    CTEST_ARGS: '-V -E boxmc|LUT'

# INTEL
build:mim:icc:single:
  extends: .build:mim:default
  variables:
    MODULES: "petsc/single-icc-19 localflock"
    SRUN_OPTIONS: "--time 02:00:00 --mem 8G -n 9"
    PETSC_OPTIONS: "-vecscatter_type mpi1"

build:mim:icc:debug:
  extends: .build:mim:default
  variables:
    MODULES: "petsc/single-icc-19 localflock"
    SRUN_OPTIONS: "--time 02:00:00 --mem 8G -n 9"
    PETSC_OPTIONS: "-vecscatter_type mpi1"
    BUILD_TYPE: DEBUG


# GCC
build:mim:gcc:single:
  extends: .build:mim:default
  variables:
    MODULES: "petsc/single-gcc-9 localflock"

build:mim:gcc:debug:
  extends: .build:mim:default
  variables:
    MODULES: "petsc/debug-gcc-9 localflock"
    BUILD_TYPE: DEBUG

build:mim:gcc:debug:gcov:
  extends: .build:mim:default
  after_script:
    -  bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
  extends: .build:mim:default
  variables:
    MODULES: "petsc/debug-gcc-9 localflock"
    BUILD_TYPE: DEBUG
    CODECOV_TOKEN: "0d3305f8-b2e2-404e-9218-92a749eb7e5b"
    CMAKE_OPTS: "-DENABLE_GCOV=ON"
