#!/usr/bin/env bash
# Prerequisites for the Tenstream solver are
#
#  *cmake
#  *PETSc
#  *NETCDF
#  *MPI
#
# Instructions on how to install these is beyond the scope of this text.
#
# You may find a hint for a suitable config file in the config/ directory:
#

# If you are lucky, you work at the Meteorological Institute Munich,
# just follow the steps in config/lmu_mim.cmake
#
# README.zmaw provides installation instructions for the MPI Hamburg environment
#
# If you found yourself go nuts because of compile errors,
# please consider providing installation instructions for your enviroment.
#
##########################################################################################################

# Confirm that we use the correct mpi
which mpif90

# If you dont have an up to date and working petsc installation, the install process might be something like
export PETSC_DIR=~/petsc-maint

git clone -b maint https://bitbucket.org/petsc/petsc $PETSC_DIR

cd $PETSC_DIR
export PETSC_ARCH=mypetsc
./configure                             \
    --with-cc=$(which mpicc)            \
    --with-fc=$(which mpif90)           \
    --with-cxx=$(which mpic++)          \
    --with-fortran                      \
    && make all

# and put the environment variables in your bashrc
cat >> ~/.bashrc <<EOF
#PETSC Installation
export PETSC_DIR=$PETSC_DIR
export PETSC_ARCH=mypetsc
EOF

# Then check if PETSC works:
cd $PETSC_DIR && make check

# Optional steps before you start:
#
# You may want to override the lut_basename, the path where the tenstream solver will put the lookuptables
# the default is otherwise local job directory. -- see src/optprop_parameters.f90
# lut_basename should be a path, that is reachable for mpi_node==0.
# and if possible globally reachable so that we dont have to compute the lookuptables over and over again.
# The lut_basename may also be provided as a commandline option: -lut_basename /global_reachable_path/LUT
# or simply put in a ~/.petscrc or ./.petscrc
echo "-lut_basename /global_reachable_path/LUT" >> ~/.petscrc

# Next step is to set the paths for additional libraries and thus provide a config file
# Check the appropriate files in config/*

#Then build tenstream
cd $TENSTREAM_DIR
mkdir build && cd build
cmake .. && make -j

# Check the tenstream runtime options with 
./bin/petsc_solver -show_options

# For a first example you could run
mpirun -np 2 ./bin/petsc_solver -ident run_test -dx 70
# Note that creating the Lookuptables takes a loong time.... dont be discouraged if you run it for the first time.

# If that does not throw a lot of errors ---
# well, then... Congratulations !!, you successfully installed the tenstream solver.
# Be proud, this is not an easy task!

# You are now ready to proceed to your libRadtran installation....

# If you installed everything and are ready to run it, please also check the solver options.
# For examples look in doc/petscrc_example
